### ISSUE TITLE
How to remove a column from a dataframe in R? 

### ISSUE THREAD

**Issue by Liliooon** [r-classes/ds4dh-hw1-Liliooon#1]
Could you please tell me how can one remove an entire column from a dataframe in R? Here is an example of dataframe from which I want to remove the third column:
```
  name age student
1 Ivan  18    TRUE
2 Lena  29   FALSE
3 Vika  23    TRUE
```

**Comment by agricolamz** [comment]
I'd do it this way:

```
df <- df[,-3]
```
